version : "3"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&"
    
    depends_on:
      - db

  db:
    image: postgres
    