# Generated by Django 2.0 on 2019-01-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190112_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
