# Generated by Django 2.0 on 2019-01-16 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190116_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_studying',
        ),
        migrations.DeleteModel(
            name='ClassRoom',
        ),
    ]
