# Generated by Django 2.0 on 2019-01-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190117_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
