# Generated by Django 2.0 on 2019-01-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190117_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='serial_no',
            field=models.FloatField(default=1, primary_key=True, serialize=False),
        ),
    ]
