# Generated by Django 2.0 on 2019-01-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20190117_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='position',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='university',
        ),
    ]
