# Generated by Django 2.2 on 2019-06-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20190118_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='serial_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
