# Generated by Django 2.2 on 2019-06-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20190604_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='serial_no',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
